lvl2_task3/todo/tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name="list"),
	path('update_task/<str:pk>/', views.updateTask, name="update_task"),
	path('delete/<str:pk>/', views.deleteTask, name="delete"),
]

lvl2_task3/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))

]

lvl2_task3/todo/tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
	title = models.CharField(max_length=200)
	complete = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

lvl2_task3/todo/tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import *


class TaskForm(forms.ModelForm):
	title= forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new task...'}))

	class Meta:
		model = Task
		fields = '__all__'

lvl2_task3/todo/tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *
from .forms import *

# Create your views here.

def index(request):
	tasks = Task.objects.all()

	form = TaskForm()

	if request.method =='POST':
		form = TaskForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('/')


	context = {'tasks':tasks, 'form':form}
	return render(request, 'tasks/list.html', context)

def updateTask(request, pk):
	task = Task.objects.get(id=pk)

	form = TaskForm(instance=task)

	if request.method == 'POST':
		form = TaskForm(request.POST, instance=task)
		if form.is_valid():
			form.save()
			return redirect('/')

	context = {'form':form}

	return render(request, 'tasks/update_task.html', context)

def deleteTask(request, pk):
	item = Task.objects.get(id=pk)

	if request.method == 'POST':
		item.delete()
		return redirect('/')

	context = {'item':item}
	return render(request, 'tasks/delete.html', context)

lvl2_task3/todo/tasks/templates/tasks/copied.html
<!-------------------------------------------------------------------->

{%load static%}

<head>
	<meta charset="UTF-8">
	<meta name = "viewport" content = "width = device-width, initial-scale=1.0">
</head>
<style>
	@import url('https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap');
*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins',sans-serif;
}
body{
    overflow: hidden;
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    background-color: black;
}
section{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;

}
.box{
    position: relative;
}

.box .square{
    position: absolute;
    backdrop-filter: blur(5px);
    box-shadow: 0 25px 45px rgba(0,0,0,0.1);
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
    background: rgba(255,255,255,0.1);
    border-radius: 10px;
}


.container{
    position: relative;
    width: 400px;
    min-height: 400px;
    background: rgba(255,255,255,0.1);
    border-radius: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
    backdrop-filter: blur(5px);
    box-shadow: 0 25px 45px rgba(0,0,0,0.1);
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
    transform-style: preserve-3d;
    perspective: 1000px;
}


.form{
    position: relative;
    width: 100%;
    height: 100%;
    padding: 40px;
}

.form h2{
    position: relative;
    color: #fff;
    font-size: 24px;
    font-weight: 600;
    letter-spacing: 1px;
    margin-bottom: 40px;
}

.form h2::before{
    content: '';
    position: absolute;
    left: 0px;
    bottom: -10px;
    width: 80px;
    height: 4px;
    background: #fff;
}

.form .inputbox{
    width: 100%;
    margin-top: 20px;
}

.form .inputbox input{
    width: 100%;
    background: rgba(255,255,255,0.2);
    border: none;
    outline: none;
    padding: 10px 20px;
    border-radius: 35px;
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
    font-size: 16px;
    letter-spacing: 1px;
    color: #fff;
    box-shadow: 0 5px 15px rgba(0,0,0,0.05);
}
.form .inputbox {
    color: #fff; 
}
.form .inputbox input[type="submit"]{
    background: #fff;
    color: #666;
    max-width: 100px;
    cursor: ponter;
    margin-bottom: 20px;
    font-weight: 600;
}

.forget{
    margin-top: 5px;
    color: #fff;
}

.forget a{
    color: #fff;
    font-weight: 600;
}

input::placeholder {
	width: 100%;
    margin-top: 20px;
    background: rgba(255,255,255,0.2);
    border: none;
    outline: none;
    padding: 10px 20px;
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
    font-size: 16px;
    letter-spacing: 1px;
    box-shadow: 0 5px 15px rgba(0,0,0,0.05);
    color: #666;
    max-width: 100px;
    cursor: ponter;
    margin-bottom: 20px;
    font-weight: 600;
}
</style>
<body style="background-image: url('{%static 'images/1.jpg'%}');">
	<section>
		<div class="box" id="form">
			<div class="container">
				<div class="form">
					<h2>A Simple To do</h2>
					<form method="POST" action="/">
						{% csrf_token %}
						{{form.title}}
						<div class="inputbox">
							<input type="submit" value="Create">
						</div>
					</form>
                </div>
            </div>
        </div>
    </section>
</body>

<div class="todo-list">

	{% for task in tasks %}
		<div class="item-row">
			<a class="btn btn-sm btn-info" href="{% url 'update_task' task.id %}">Update</a>
			<a class="btn btn-sm btn-danger" href="{% url 'delete' task.id %}">Delete</a>

			{% if task.complete == True %}
			<strike>{{task}}</strike>
			{% else %}
			<span>{{task}}</span>
			{% endif %}
		</div>
	{% endfor %}
</div>

lvl2_task3/todo/tasks/templates/tasks/delete.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{%load static%}
<style>

	.p{
		position: relative;
		color: #fff;
		font-size: 24px;
		font-weight: 600;
		letter-spacing: 1px;
		margin-bottom: 40px;
	}
	input{
		color: white;
		width: 100%;
		padding: 8px 20px;
		margin: 8px 0;
		box-sizing: border-box;
		border:  red 2px solid;
		border-radius: 35px;
		background-color: transparent;
	}

	input::placeholder {
	  color : white;
	}


	.submit{
		background-color: #6BA3E8;
		
	}

	.center-column{
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		width:600px;
		margin: 20px auto;
		padding:20px;
		border-radius: 35px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		backdrop-filter: blur(3px) saturate(180%);
		-webkit-backdrop-filter: blur(5px) saturate(180%);
		background-color: rgba(17, 25, 40, 0.75);
		border-radius: 12px;
		border: 1px solid rgba(255, 255, 255, 0.125);
	}

</style>
<body style="background-image: url('{%static 'images/1.jpg'%}');">
<div class="center-column">
	<p style="color:white">Are you sure you want to delete the task "{{item}}" ?</p>
		<form method="POST" action="">
			{% csrf_token %}
			<input type="submit" class="button_active" formaction="{% url 'list' %}" value="Cancel">
			<input type="submit" value="Delete">
		</form>
	</form>
</div>
</body>


lvl2_task3/todo/tasks/templates/tasks/list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Playfair+Display:wght@500&display=swap" rel="stylesheet">
{%load static%}
<style>


	.both{
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}
	input{
		color: white;
		width: 100%;
		padding: 10px 20px;
		margin: 8px 0;
		box-sizing: border-box;
		border:  red 2px solid;
		border-radius: 35px;
		background-color: transparent;
	}

	input::placeholder {
	  color : white;
	}

	.submit{
		background-color: #6BA3E8;
		
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		border-radius: 35px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		backdrop-filter: blur(3px) saturate(180%);
		-webkit-backdrop-filter: blur(5px) saturate(180%);
		background-color: rgba(17, 25, 40, 0.75);
		border-radius: 12px;
		border: 1px solid rgba(255, 255, 255, 0.125);
	}

	.item-row{
		background-color: transparent;
		margin: 10px;
		padding: 5px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: transparent;

	}

	.btn{
		border-radius: 35px;
		background-color: transparent;
	}

	article {
		font-size: 2vmin;
		font-family: 'Aboreto', cursive;
		background: linear-gradient(
			to right, 
			hsl(98 100% 62%), 
			hsl(204 100% 59%)
		);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		text-align: center;
	}

	h1 {
		font-weight: medium;
		font-size: 5vmin;
		line-height: 1.1;
}
	

</style>
<div class="both">
	<body style="background-image: url('{%static 'images/1.jpg'%}');">
		<div class="center-column">
			<article>
				<h1>A Simple To-Do</h1>
				<p>developed using django by enayat.</p>
			</article>
			<form method="POST" action="/">
				{% csrf_token %}
				{{form.title}}
				<input class="btn btn-info" type="submit" value="Create">
			</form>
		</div>

		<div class="center-column">
			<div class="todo-list">
				<article class="task_list">Tasks will Appear here ! </article>
				{% for task in tasks %}
					<div class="item-row">
						<a class="btn btn-sm btn-info" href="{% url 'update_task' task.id %}">Update</a>
						<a class="btn btn-sm btn-danger" href="{% url 'delete' task.id %}">Delete</a>
						{% if task.complete == True %}
						<strike style='color:red'>
							<span style='color:white'>{{task}}<span>
						</strike>
						{% else %}
						<span>{{task}}</span>
						{% endif %}
					</div>
				{% endfor %}
			</div>
		</div>
	</body>
</div>


lvl2_task3/todo/tasks/templates/tasks/update_task.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{%load static%}
<style>

	.p{
		position: relative;
		color: #fff;
		font-size: 24px;
		font-weight: 600;
		letter-spacing: 1px;
		margin-bottom: 40px;
	}
	input{
		color: white;
		width: 100%;
		padding: 10px 20px;
		margin: 8px 0;
		box-sizing: border-box;
		border:  #6BA3E8 2px solid;
		border-radius: 35px;
		background-color: transparent;
	}
	


	input::placeholder {
	  color : white;
	}


	.submit{
		background-color: #6BA3E8;
		
	}

	.center-column{
		color: white;
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		width:600px;
		margin: 20px auto;
		padding:10px;
		border-radius: 35px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		backdrop-filter: blur(3px) saturate(180%);
		-webkit-backdrop-filter: blur(5px) saturate(180%);
		background-color: rgba(17, 25, 40, 0.75);
		border-radius: 12px;
		border: 1px solid rgba(255, 255, 255, 0.125);
	}

	#id_complete{
		width: 18px;
		height: 18px;
		position: absolute;
		margin: 4px;
	}

</style>
<body style="background-image: url('{%static 'images/1.jpg'%}');">
<div class="center-column">
	<p style="color:white; text-align: center;">Update Task ?</p>
		<form method="POST" action="">
			{% csrf_token %}
			{{form}}
			<input type="submit" value="Update Task">
		</form>
</div>
</body>